
import { Template } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'vn-travel-1',
    title: 'Minimal Travel Vlog',
    editor: 'VN',
    tags: ['Reels', 'Travel', 'Clean'],
    imageUrl: 'https://picsum.photos/seed/vn-travel-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr1/300/300',
  },
  {
    id: 'capcut-action-1',
    title: 'Dynamic Action Opener',
    editor: 'CapCut',
    tags: ['Action', 'Intro', 'Fast'],
    imageUrl: 'https://picsum.photos/seed/capcut-action-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr2/300/300',
  },
  {
    id: 'vn-food-1',
    title: 'Tasty Food Recipe',
    editor: 'VN',
    tags: ['Food', 'Cooking', 'Bright'],
    imageUrl: 'https://picsum.photos/seed/vn-food-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr3/300/300',
  },
  {
    id: 'capcut-fashion-1',
    title: 'Chic Fashion Lookbook',
    editor: 'CapCut',
    tags: ['Fashion', 'Beauty', 'Elegant'],
    imageUrl: 'https://picsum.photos/seed/capcut-fashion-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr4/300/300',
  },
  {
    id: 'vn-reels-1',
    title: 'Viral Dance Trend',
    editor: 'VN',
    tags: ['Reels', 'Dance', 'Trending'],
    imageUrl: 'https://picsum.photos/seed/vn-reels-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr5/300/300',
  },
  {
    id: 'capcut-retro-1',
    title: '80s Retro Wave',
    editor: 'CapCut',
    tags: ['Retro', 'Synthwave', 'Vibrant'],
    imageUrl: 'https://picsum.photos/seed/capcut-retro-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr6/300/300',
  },
  {
    id: 'vn-corporate-1',
    title: 'Clean Corporate Slideshow',
    editor: 'VN',
    tags: ['Business', 'Corporate', 'Minimal'],
    imageUrl: 'https://picsum.photos/seed/vn-corporate-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr7/300/300',
  },
  {
    id: 'capcut-gaming-1',
    title: 'Epic Gaming Montage',
    editor: 'CapCut',
    tags: ['Gaming', 'Esports', 'Intense'],
    imageUrl: 'https://picsum.photos/seed/capcut-gaming-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr8/300/300',
  },
  {
    id: 'vn-nature-1',
    title: 'Serene Nature Moments',
    editor: 'VN',
    tags: ['Nature', 'Calm', 'Cinematic'],
    imageUrl: 'https://picsum.photos/seed/vn-nature-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr9/300/300',
  },
  {
    id: 'capcut-lyric-1',
    title: 'Aesthetic Lyric Video',
    editor: 'CapCut',
    tags: ['Music', 'Lyrics', 'Aesthetic'],
    imageUrl: 'https://picsum.photos/seed/capcut-lyric-1/600/800',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    qrCodeUrl: 'https://picsum.photos/seed/qr10/300/300',
  },
];
